from fastapi import APIRouter
from app.api.v1 import auth,teams,team_requests,tournaments,match_rooms,result_submissions,profile,notifications,organizer_requests,admin,leaderboard,winner,dashboard,match_registrations,match_results,prizes
api_router=APIRouter()
api_router.include_router(auth.router,prefix='/auth',tags=['Auth'])
api_router.include_router(admin.router,prefix='/admin',tags=['Admin'])
api_router.include_router(notifications.router,prefix='/notifications',tags=['Notifications'])
api_router.include_router(profile.router,prefix='/profile',tags=['Profile'])
api_router.include_router(tournaments.router,prefix='/tournaments',tags=['Tournaments'])
api_router.include_router(teams.router,prefix='/teams',tags=['Teams'])
api_router.include_router(match_rooms.router,prefix='/matchrooms',tags=['Match Rooms'])
api_router.include_router(match_registrations.router,prefix='/matchregistrations',tags=['Match Registrations'])
api_router.include_router(match_results.router,prefix='/matchresults',tags=['Match Results'])
api_router.include_router(leaderboard.router,prefix='/leaderboard',tags=['Leaderboard'])
api_router.include_router(winner.router,prefix='/winner',tags=['Winner'])
api_router.include_router(dashboard.router,prefix='/dashboard',tags=['Dashboard'])
api_router.include_router(team_requests.router,prefix='/team-requests',tags=['Team Requests'])
api_router.include_router(prizes.router,prefix='/prizes',tags=['Prizes'])
api_router.include_router(result_submissions.router,prefix='/result-submissions',tags=['Result Submissions'])
api_router.include_router(organizer_requests.router,prefix='/organizer-requests',tags=['Organizer Requests'])
